# Generated by Django 4.1.7 on 2023-05-03 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_rename_blogs_trendingblogs_blogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author_blog",
                to="blog.authors",
            ),
        ),
        migrations.AlterField(
            model_name="usercomments",
            name="blogs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_comment",
                to="blog.blogs",
            ),
        ),
        migrations.AlterField(
            model_name="usercomments",
            name="message",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="Category")),
                (
                    "blogs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_blog",
                        to="blog.blogs",
                    ),
                ),
            ],
        ),
    ]
