# Generated by Django 4.1.7 on 2023-05-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blogs_author_alter_usercomments_blogs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categories",
            name="blogs",
        ),
    ]
