# Generated by Django 4.1.7 on 2023-05-03 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_remove_categories_blogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_blog",
                to="blog.categories",
            ),
        ),
    ]
