# Generated by Django 4.1.7 on 2023-05-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_blogs_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
